language: php
php:
  - "7.1"
before_script:
  - composer install
script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
services: ~
after_success:
  - travis_retry php vendor/bin/coveralls -v